# Generated by Django 5.1.6 on 2025-06-23 19:55

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='HaridorDukon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('egasi', models.CharField(max_length=255)),
                ('joylashuvi', models.TextField()),
                ('dukon_rasmi', models.ImageField(upload_to='dukons/')),
                ('egasining_rasmi', models.ImageField(upload_to='egalar/')),
            ],
        ),
        migrations.CreateModel(
            name='MahsulotTuri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('type', models.CharField(choices=[('pazanda', 'Pazanda'), ('yetkazib_beruvchi', 'Yetkazib Beruvchi'), ('ega', 'Ega')], max_length=20)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('tg_id', models.CharField(blank=True, max_length=100, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('rasmi', models.ImageField(upload_to='mahsulotlar/')),
                ('narxi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('miqdori', models.FloatField(default=0)),
                ('turi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mahsulotturi')),
            ],
        ),
        migrations.CreateModel(
            name='Pazanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuliq_ismi', models.CharField(max_length=255)),
                ('turi', models.CharField(max_length=100)),
                ('rasmi', models.ImageField(upload_to='pazandalar/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MiqdorQoshish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaqt_sana', models.DateTimeField(auto_now_add=True)),
                ('miqdor', models.FloatField()),
                ('tasdiqlangan', models.BooleanField(default=False)),
                ('ariza_text', models.TextField(blank=True, null=True)),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mahsulot')),
                ('pazanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pazanda')),
            ],
        ),
        migrations.CreateModel(
            name='YetkazibBeruvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuliq_ismi', models.CharField(max_length=255)),
                ('rasmi', models.ImageField(upload_to='yetkazib/')),
                ('bmh', models.TextField(verbose_name='Biriktirilgan mashina haqida')),
                ('bmr', models.ImageField(upload_to='mashina_rasmlar/')),
                ('mahsulotlar', models.ManyToManyField(blank=True, to='main.mahsulot')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Savdo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaqt_sana', models.DateTimeField(auto_now_add=True)),
                ('oluvchining_ismi', models.CharField(max_length=255)),
                ('smm', models.FloatField(verbose_name='Sotilgan mahsulot miqdori')),
                ('smr', models.ImageField(upload_to='savdo/')),
                ('st', models.CharField(choices=[('naqd', 'Naqd'), ('karta', 'Karta'), ('nasiya', 'Nasiya')], max_length=20)),
                ('tulandi', models.BooleanField(default=False)),
                ('tasdiq_kutilmoqda', models.BooleanField(default=False)),
                ('haridor_dukon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.haridordukon')),
                ('yetkazib_beruvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.yetkazibberuvchi')),
            ],
        ),
    ]
