# Generated by Django 5.1.6 on 2025-06-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_login_user_tuliq_ismi_alter_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tel_raqami',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
