# Generated by Django 5.1.6 on 2025-06-23 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_tel_raqami'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yetkazibberuvchi',
            name='mahsulotlar',
        ),
        migrations.AddField(
            model_name='yetkazibberuvchi',
            name='mahsulotlar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
