# Generated by Django 5.1.6 on 2025-06-25 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_yetkazibberuvchi_mahsulotlar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amal_shifri', models.TextField()),
                ('sana_vaqti', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
