# Generated by Django 5.1.6 on 2025-06-29 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_amallog'),
    ]

    operations = [
        migrations.CreateModel(
            name='qaytarilgan_mahsulotlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.FloatField()),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('yq', models.BooleanField(default=False)),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mahsulot')),
            ],
        ),
    ]
