# Generated by Django 5.1.6 on 2025-07-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pazanda',
            name='turi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
