# Generated by Django 5.1.6 on 2025-07-05 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_pazanda_turi'),
    ]

    operations = [
        migrations.CreateModel(
            name='YuklamaSorov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('done', 'Done'), ('waiting', 'kutilmoqda')], max_length=20)),
                ('miqdor', models.FloatField()),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('tasdiq', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
