# Generated by Django 5.1.6 on 2025-07-05 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_yuklamasorov'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yuklamasorov',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.yetkazibberuvchi'),
        ),
    ]
