# Generated by Django 5.1.6 on 2025-07-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_yuklamasorov_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yuklamasorov',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
