# Generated by Django 5.1.6 on 2025-07-05 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_yuklamasorov_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='yuklamasorov',
            name='mahsulot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.mahsulot'),
        ),
    ]
