# Generated by Django 5.1.6 on 2025-07-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_yuklamasorov_mahsulot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yuklamasorov',
            name='mode',
            field=models.CharField(choices=[('done', 'Done'), ('waiting', 'kutilmoqda'), ('rejected', 'Rad etildi')], max_length=20),
        ),
    ]
