# Generated by Django 5.1.6 on 2025-07-06 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_yuklamasorov_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='yuklamasorov',
            name='pazanda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pazanda'),
        ),
    ]
