# Generated by Django 5.1.6 on 2025-07-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_yuklamasorov_pazanda'),
    ]

    operations = [
        migrations.AddField(
            model_name='miqdorqoshish',
            name='rasmi',
            field=models.ImageField(blank=True, null=True, upload_to='miqdor_qoshish/'),
        ),
    ]
