# Generated by Django 5.1.6 on 2025-07-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_miqdorqoshish_rasmi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savdo',
            name='smm',
            field=models.TextField(blank=True, null=True, verbose_name='Sotilgan mahsulot miqdori'),
        ),
    ]
