# Generated by Django 5.1.6 on 2025-07-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_savdo_smm'),
    ]

    operations = [
        migrations.AddField(
            model_name='savdo',
            name='summa',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
