# Generated by Django 5.1.15 on 2026-01-24 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_savdo_summa'),
    ]

    operations = [
        migrations.CreateModel(
            name='NasiyaTolov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tolov_summasi', models.FloatField()),
                ('tolov_sanasi', models.DateTimeField(auto_now_add=True)),
                ('izoh', models.TextField(blank=True, null=True)),
                ('qabul_qilgan_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('savdo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tolovlar', to='main.savdo')),
            ],
            options={
                'verbose_name': "Nasiya To'lov",
                'verbose_name_plural': "Nasiya To'lovlar",
                'ordering': ['-tolov_sanasi'],
            },
        ),
    ]
