# Generated by Django 5.1.15 on 2026-01-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_nasiyatolov'),
    ]

    operations = [
        migrations.AddField(
            model_name='haridordukon',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='haridordukon',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
