# Generated by Django 5.1.15 on 2026-02-19 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_haridordukon_latitude_haridordukon_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ADD', "Qo'shildi (Pazanda tomonidan)"), ('DEDUCT', 'Kamaytirildi (Savdo/Yuklash)'), ('RETURN', 'Qaytarildi'), ('REQUEST_APPROVED', 'Sorov tasdiqlandi'), ('ADJUST', 'Admin tomonidan tuzatildi')], max_length=20)),
                ('old_qty', models.FloatField()),
                ('new_qty', models.FloatField()),
                ('delta', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mahsulot')),
                ('yetkazib_beruvchi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.yetkazibberuvchi')),
            ],
            options={
                'verbose_name': 'Zaxira tarixi',
                'verbose_name_plural': 'Zaxira tarixlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mahsulot')),
                ('yetkazib_beruvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='main.yetkazibberuvchi')),
            ],
            options={
                'verbose_name': 'Yetkazib beruvchi zaxirasi',
                'verbose_name_plural': 'Yetkazib beruvchilar zaxiralari',
                'unique_together': {('yetkazib_beruvchi', 'mahsulot')},
            },
        ),
    ]
