# Generated by Django 5.1.15 on 2026-02-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_stockhistory_deliverystock'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='min_miqdori',
            field=models.FloatField(default=10, help_text="Bu miqdordan kam bo'lsa ogohlantirish chiqadi"),
        ),
    ]
