# Generated by Django 4.2.9 on 2026-03-19 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_company_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_on_trial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='setup_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='setup_mode',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='trial_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
