# Generated by Django 4.2.9 on 2026-03-19 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_company_is_on_trial_company_setup_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='has_map',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='yetkazibberuvchi',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yetkazibberuvchi',
            name='last_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yetkazibberuvchi',
            name='last_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.company')),
                ('yetkazib_beruvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='main.yetkazibberuvchi')),
            ],
            options={
                'verbose_name': 'Joylashuv tarixi',
                'verbose_name_plural': 'Joylashuv tarixlari',
                'ordering': ['-timestamp'],
            },
        ),
    ]
