# Generated by Django 4.2.9 on 2026-03-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_plan_has_map_yetkazibberuvchi_last_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='haridordukon',
            name='telefon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='haridordukon',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
