# Generated by Django 4.2.9 on 2026-03-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_haridordukon_telefon_haridordukon_telegram_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='custom_backup_type',
            field=models.CharField(choices=[('none', "Yo'q"), ('monthly', 'Oylik'), ('weekly', 'Haftalik'), ('daily', 'Kunlik')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='custom_has_analytics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='custom_has_map',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='custom_has_telegram_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='custom_max_users',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='company',
            name='custom_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='company',
            name='is_custom_plan',
            field=models.BooleanField(default=False),
        ),
    ]
