# Generated by Django 4.2.9 on 2026-03-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_company_custom_backup_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='last_backup_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='backup_type',
            field=models.CharField(choices=[('none', "Yo'q"), ('monthly', 'Oylik'), ('weekly', 'Haftalik'), ('daily', 'Kunlik')], default='none', max_length=20),
        ),
    ]
