# Generated by Django 4.2.9 on 2026-03-24 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_company_last_backup_at_plan_backup_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_custom', models.BooleanField(default=False)),
                ('custom_max_users', models.IntegerField(default=5)),
                ('custom_has_telegram_bot', models.BooleanField(default=False)),
                ('custom_has_analytics', models.BooleanField(default=False)),
                ('custom_has_map', models.BooleanField(default=False)),
                ('custom_backup_type', models.CharField(choices=[('none', "Yo'q"), ('monthly', 'Oylik'), ('weekly', 'Haftalik'), ('daily', 'Kunlik')], default='none', max_length=20)),
                ('custom_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_requests', to='main.company')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.plan')),
            ],
        ),
    ]
