# Generated by Django 5.1.15 on 2026-03-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_planrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='next_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='payment_status',
            field=models.CharField(choices=[('paid', "To'langan"), ('unpaid', "To'lanmagan")], default='paid', max_length=20),
        ),
    ]
