# Generated by Django 4.2.9 on 2026-03-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_company_next_payment_date_company_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='custom_backup_type',
            field=models.CharField(choices=[('none', "Yo'q ($0)"), ('monthly', 'Oylik ($5)'), ('weekly', 'Haftalik ($15)'), ('daily', 'Kunlik ($30)')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='plan',
            name='backup_type',
            field=models.CharField(choices=[('none', "Yo'q ($0)"), ('monthly', 'Oylik ($5)'), ('weekly', 'Haftalik ($15)'), ('daily', 'Kunlik ($30)')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='planrequest',
            name='custom_backup_type',
            field=models.CharField(choices=[('none', "Yo'q ($0)"), ('monthly', 'Oylik ($5)'), ('weekly', 'Haftalik ($15)'), ('daily', 'Kunlik ($30)')], default='none', max_length=20),
        ),
    ]
