# Generated by Django 4.2.9 on 2026-03-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_company_custom_backup_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savdo',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savdo',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
