# Generated by Django 4.2.9 on 2026-03-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_savdo_latitude_savdo_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='has_used_trial',
            field=models.BooleanField(default=False),
        ),
    ]
