# Generated by Django 4.2.9 on 2026-03-26 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_company_has_used_trial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_trans_id', models.CharField(max_length=255)),
                ('merchant_trans_id', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('action', models.IntegerField(default=0)),
                ('sign_time', models.CharField(max_length=255)),
                ('sign_string', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('processing', 'Jarayonda'), ('paid', "To'langan"), ('canceled', 'Bekor qilingan'), ('error', 'Xatolik')], default='processing', max_length=20)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('perform_time', models.DateTimeField(blank=True, null=True)),
                ('cancel_time', models.DateTimeField(blank=True, null=True)),
                ('error_reason', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_transactions', to='main.company')),
            ],
        ),
    ]
