# Generated by Django 4.2.9 on 2026-03-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_clicktransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='payment_status',
            field=models.CharField(choices=[('paid', "To'langan"), ('unpaid', "To'lanmagan")], default='unpaid', max_length=20),
        ),
    ]
