# Generated by Django 4.2.9 on 2026-03-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_company_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='planrequest',
            name='is_trial',
            field=models.BooleanField(default=False),
        ),
    ]
