# Generated by Django 5.1.15 on 2026-04-06 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_user_username_per_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
