# Generated by Django 5.0.6 on 2026-06-11 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_user_rasm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appnotification',
            name='company',
        ),
        migrations.RemoveIndex(
            model_name='clicktransaction',
            name='main_clickt_merchan_6e3d6b_idx',
        ),
        migrations.RemoveIndex(
            model_name='clicktransaction',
            name='main_clickt_status_2fe156_idx',
        ),
        migrations.RemoveField(
            model_name='clicktransaction',
            name='click_paydoc_id',
        ),
        migrations.RemoveField(
            model_name='clicktransaction',
            name='service_id',
        ),
        migrations.AddField(
            model_name='qaytarilgan_mahsulotlar',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='clicktransaction',
            name='click_trans_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='warehouse_type',
            field=models.CharField(choices=[('finished', 'Tayyor mahsulotlar ombori'), ('semi_finished', 'Ombor mahsulotlari')], default='finished', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='event_type',
            field=models.CharField(choices=[('ADD', "Qo'shildi (Ishlab chiqaruvchi tomonidan)"), ('DEDUCT', 'Kamaytirildi (Savdo/Yuklash)'), ('RETURN', 'Qaytarildi'), ('REQUEST_APPROVED', 'Sorov tasdiqlandi'), ('RAW_REQUESTED', "Ishlab chiqarish uchun so'rov yuborildi"), ('RAW_APPROVED', 'Ombor mahsuloti berildi'), ('RAW_REJECTED', "Ombor mahsuloti so'rovi rad etildi"), ('ADJUST', 'Admin tomonidan tuzatildi')], max_length=20),
        ),
        migrations.DeleteModel(
            name='AppNotification',
        ),
    ]
