# Generated by Django 5.0.6 on 2026-06-11 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_add_qaytarish_status_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='haridordukon',
            name='mijoz_turi',
            field=models.CharField(choices=[('oddiy', 'Oddiy'), ('doimiy', 'Doimiy'), ('vip', 'VIP')], default='oddiy', max_length=10),
        ),
        migrations.CreateModel(
            name='DailyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField()),
                ('maqsad', models.DecimalField(decimal_places=2, help_text="Kunlik savdo maqsadi (so'm)", max_digits=14)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_targets', to='main.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kunlik maqsad',
                'verbose_name_plural': 'Kunlik maqsadlar',
                'unique_together': {('company', 'user', 'sana')},
            },
        ),
    ]
