# Generated by Django 5.0.6 on 2026-07-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_add_mijoz_turi_daily_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='tannarx',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Omborga kirim narxi (mijozga ko'rsatilmaydi)", max_digits=10),
        ),
    ]
