# Generated by Django 5.0.6 on 2026-07-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_mahsulot_tannarx'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ish_haqi_turi',
            field=models.CharField(choices=[('fixed', 'Oylik (fiksval)'), ('per_unit', 'Ishlab chiqarilgan mahsulotga qarab')], default='fixed', max_length=20),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='amortizatsiya_narxi',
            field=models.DecimalField(decimal_places=2, default=0, help_text="1 donaga to'g'ri keladigan amortizatsiya — tannarxga qo'shiladi", max_digits=10),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='ishlab_chiqarish_narxi',
            field=models.DecimalField(decimal_places=2, default=0, help_text="1 dona ishlab chiqargani uchun ishchiga to'lanadigan summa (ish_haqi_turi=per_unit bo'lsa ishlatiladi)", max_digits=10),
        ),
    ]
