# Generated by Django 5.0.6 on 2026-07-15 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_company_ish_haqi_turi_mahsulot_amortizatsiya_narxi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MahsulotRetsept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('norma_miqdor', models.FloatField(help_text="1 dona 'mahsulot' uchun kerak bo'ladigan 'komponent' miqdori")),
                ('jarima_narxi_birlik', models.DecimalField(decimal_places=2, default=0, help_text='Normadan chetlashgan har bir birlik uchun jarima summasi', max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retseptlar', to='main.company')),
                ('komponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komponent_qatorlari', to='main.mahsulot')),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retsept_qatorlari', to='main.mahsulot')),
            ],
            options={
                'verbose_name': 'Mahsulot retsepti',
                'verbose_name_plural': 'Mahsulot retseptlari',
                'unique_together': {('mahsulot', 'komponent')},
            },
        ),
    ]
