# Generated by Django 5.0.6 on 2026-07-15 16:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_mahsulotretsept'),
    ]

    operations = [
        migrations.CreateModel(
            name='QoshimchaChiqim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(help_text='Masalan: Ijara, Svet, Transport', max_length=255)),
                ('summa', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sana', models.DateField(default=django.utils.timezone.now)),
                ('izoh', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qoshimcha_chiqimlar', to='main.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Qo'shimcha chiqim",
                'verbose_name_plural': "Qo'shimcha chiqimlar",
                'ordering': ['-sana'],
            },
        ),
    ]
