# Generated by Django 5.0.6 on 2026-07-15 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_qoshimchachiqim'),
    ]

    operations = [
        migrations.AddField(
            model_name='miqdorqoshish',
            name='ish_haqi_summasi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='miqdorqoshish',
            name='jarima_summasi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='miqdorqoshish',
            name='tannarx_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productionmaterialrequest',
            name='consumed_in',
            field=models.ForeignKey(blank=True, help_text='Norma tekshiruvi vaqtida qaysi ishlab chiqarish yozuviga hisoblab chiqilgani', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumed_material_requests', to='main.miqdorqoshish'),
        ),
    ]
