# Generated by Django 5.0.6 on 2026-07-15 17:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_miqdorqoshish_ish_haqi_summasi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='serial_granularity',
            field=models.CharField(choices=[('none', "Yo'q"), ('batch', "Partiya bo'yicha (1 QR = 1 ishlab chiqarish yozuvi)"), ('unit', 'Har bir donaga alohida QR')], default='none', help_text='Ishlab chiqarishda avtomatik QR/serial yaratilsinmi', max_length=10),
        ),
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(default=uuid.uuid4, editable=False, max_length=64, unique=True)),
                ('unit_index', models.PositiveIntegerField(blank=True, help_text="Bo'sh bo'lsa — butun partiyani anglatadi", null=True)),
                ('holati', models.CharField(choices=[('omborda', 'Omborda'), ('chiqarilgan', 'Chiqarilgan')], default='omborda', max_length=20)),
                ('scan_soni', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seriallar', to='main.miqdorqoshish')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seriallar', to='main.company')),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seriallar', to='main.mahsulot')),
            ],
            options={
                'verbose_name': 'Serial',
                'verbose_name_plural': 'Seriallar',
                'ordering': ['-created_at'],
            },
        ),
    ]
