# Generated by Django 5.0.6 on 2026-07-15 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_mahsulot_serial_granularity_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='qr_tavsif',
            field=models.TextField(blank=True, default='', help_text="Public QR sahifasida ko'rsatiladigan matn (tarkib, foydalanish, ogohlantirish va h.k.)"),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='yaroqlilik_kun_soni',
            field=models.PositiveIntegerField(blank=True, help_text="Ishlab chiqarilgan sanadan necha kun yaroqli (bo'sh = muddat ko'rsatilmaydi)", null=True),
        ),
        migrations.AddField(
            model_name='serial',
            name='savdo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serials', to='main.savdo'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='holati',
            field=models.CharField(choices=[('omborda', 'Omborda'), ('chiqarilgan', 'Chiqarilgan'), ('sotilgan', 'Sotilgan')], default='omborda', max_length=20),
        ),
    ]
