# Generated by Django 5.0.6 on 2026-07-15 21:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_mahsulot_qr_tavsif_mahsulot_yaroqlilik_kun_soni_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ombor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('manzil', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='omborlar', to='main.company')),
            ],
            options={
                'verbose_name': 'Ombor',
                'verbose_name_plural': 'Omborlar',
            },
        ),
        migrations.AddField(
            model_name='productionmaterialrequest',
            name='ombor',
            field=models.ForeignKey(blank=True, help_text='Tasdiqlash vaqtida omborchi tanlaydi — qaysi ombordan berilgani', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_requests', to='main.ombor'),
        ),
        migrations.CreateModel(
            name='XodimBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(default=uuid.uuid4, editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='badge', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Xodim badge',
                'verbose_name_plural': 'Xodim badgelari',
            },
        ),
        migrations.CreateModel(
            name='OmborZaxira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.company')),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ombor_zaxiralari', to='main.mahsulot')),
                ('ombor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zaxiralar', to='main.ombor')),
            ],
            options={
                'verbose_name': 'Ombor zaxirasi',
                'verbose_name_plural': 'Ombor zaxiralari',
                'unique_together': {('ombor', 'mahsulot')},
            },
        ),
    ]
