# Generated by Django 5.0.6 on 2026-07-16 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_ombor_productionmaterialrequest_ombor_xodimbadge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='baza_tannarx',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Amortizatsiya/qo'shimcha xarajatlarsiz asosiy tannarx — distributor uchun kirim narxi, ishlab chiqaruvchi uchun retsept bo'yicha hisoblangan qism", max_digits=10),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='mahsulot_turi',
            field=models.CharField(choices=[('ishlab_chiqariladigan', 'Ishlab chiqariladigan (retsept asosida)'), ('distributor', 'Distributor (tayyor sotib olinadigan)')], default='ishlab_chiqariladigan', help_text="Faqat 'finished' turdagi mahsulotlar uchun ma'noli", max_length=25),
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='tannarx',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Yakuniy tannarx — avtomatik hisoblanadi, qo'lda tahrirlanmaydi", max_digits=10),
        ),
        migrations.CreateModel(
            name='MahsulotQoshimchaXarajat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(help_text='Masalan: Tashish, Bojxona', max_length=255)),
                ('summa', models.DecimalField(decimal_places=2, help_text="1 donaga to'g'ri keladigan qo'shimcha xarajat", max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.company')),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qoshimcha_xarajatlar', to='main.mahsulot')),
            ],
            options={
                'verbose_name': "Mahsulot qo'shimcha xarajati",
                'verbose_name_plural': "Mahsulot qo'shimcha xarajatlari",
            },
        ),
    ]
