# Generated by Django 5.0.6 on 2026-07-16 05:07

from django.db import migrations, models


def backfill_baza_tannarx(apps, schema_editor):
    Mahsulot = apps.get_model('main', 'Mahsulot')
    Mahsulot.objects.exclude(tannarx=0).update(baza_tannarx=models.F('tannarx'))


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_mahsulot_baza_tannarx_mahsulot_mahsulot_turi_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_baza_tannarx, noop),
    ]
