# Generated by Django 5.0.6 on 2026-07-16 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_backfill_baza_tannarx'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='ombor_turi',
            field=models.CharField(choices=[('xom_ashyo', 'Xom ashyo'), ('yarim_tayyor', 'Yarim tayyor mahsulot')], default='xom_ashyo', help_text="Faqat 'semi_finished' mahsulotlar uchun ma'noli", max_length=20),
        ),
        migrations.CreateModel(
            name='PazandaMahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.company')),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masul_ishlab_chiqaruvchilar', to='main.mahsulot')),
                ('pazanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biriktirilgan_mahsulotlar', to='main.pazanda')),
            ],
            options={
                'verbose_name': 'Ishlab chiqaruvchiga biriktirilgan mahsulot',
                'verbose_name_plural': 'Ishlab chiqaruvchiga biriktirilgan mahsulotlar',
                'unique_together': {('pazanda', 'mahsulot')},
            },
        ),
    ]
