# Generated by Django 5.0.6 on 2026-07-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_mahsulot_ombor_turi_pazandamahsulot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mahsulot',
            name='amortizatsiya_narxi',
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='amortizatsiya_foizi',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Foizda (masalan 10 = 10%) — baza tannarx + qo'shimcha xarajatlar yig'indisiga ustama sifatida qo'shiladi", max_digits=5),
        ),
    ]
