# Generated by Django 5.0.6 on 2026-07-16 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_remove_mahsulot_amortizatsiya_narxi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mahsulotretsept',
            name='jarima_narxi_birlik',
        ),
    ]
