# Generated by Django 5.0.6 on 2026-07-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_remove_mahsulotretsept_jarima_narxi_birlik'),
    ]

    operations = [
        migrations.AddField(
            model_name='savdo',
            name='foyda',
            field=models.FloatField(default=0, help_text="Sof foyda snapshoti: sotuv paytidagi (narx - tannarx) * miqdor yig'indisi. Kredit ustamasini o'z ichiga olmaydi — faqat mahsulot sotuvidan kelgan foyda."),
        ),
    ]
