# Generated by Django 5.0.6 on 2026-07-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_savdo_foyda'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='desktop_agent_token',
            field=models.CharField(blank=True, editable=False, help_text="Desktop Agent dasturi shu firmaning ma'lumotlariga (omborlar ro'yxati) kirishi uchun token.", max_length=64, null=True, unique=True),
        ),
    ]
