# Generated by Django 5.0.6 on 2026-07-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_company_desktop_agent_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionmaterialrequest',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, help_text='Ishlab chiqaruvchi Desktop Agent orqali "Qabul qildim" deb belgilagan vaqt (status\'ga ta\'sir qilmaydi, faqat ma\'lumot uchun)', null=True),
        ),
    ]
