# Generated by Django 5.0.6 on 2026-07-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_production_material_request_acknowledged_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='custom_desktop_agent_stations',
            field=models.PositiveIntegerField(default=0, help_text="Sotib olingan Desktop Agent stansiyalari soni (donasiga oyiga $60.00). Faqat aloqa orqali (superadmin tomonidan) belgilanadi — firma egasi o'zi so'ray olmaydi."),
        ),
    ]
