# Generated by Django 5.0.6 on 2026-07-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0073_desktop_agent_stations_addon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('pazanda', 'Ishlab chiqaruvchi'), ('ishlab_chiqaruvchi', 'Ishlab chiqaruvchi'), ('omborchi', 'Omborchi'), ('savdogar', 'Savdogar'), ('yetkazib_beruvchi', 'Yetkazib Beruvchi'), ('desktop_agent', 'Desktop Agent'), ('ega', 'Ega')], max_length=20),
        ),
    ]
