# Generated by Django 5.0.6 on 2026-07-20 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0074_user_type_desktop_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='planrequest',
            name='custom_desktop_agent_stations',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
