# Generated by Django 5.0.6 on 2026-07-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0076_productionmaterialrequest_kod'),
    ]

    operations = [
        migrations.AddField(
            model_name='ombor',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ombor',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
