# Generated by Django 5.0.6 on 2026-07-25 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0077_ombor_latitude_ombor_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='XodimDavomat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('kirish', 'Keldi'), ('chiqish', 'Ketdi')], max_length=10)),
                ('vaqt', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='davomatlar', to='main.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='davomat_hodisalari', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Xodim davomati',
                'verbose_name_plural': 'Xodim davomatlari',
                'ordering': ['-vaqt'],
            },
        ),
    ]
