# Generated by Django 5.0.6 on 2026-07-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0078_xodimdavomat'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_agent_heartbeat',
            field=models.DateTimeField(blank=True, help_text="Desktop Agent stansiyasi (type='desktop_agent') fondan har ~25 soniyada yuboradigan 'tirik ekanligi' signalining oxirgi vaqti — online/oflayn holatini aniqlash uchun.", null=True),
        ),
    ]
