# Generated by Django 5.0.6 on 2026-07-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0079_user_last_agent_heartbeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulotqoshimchaxarajat',
            name='turi',
            field=models.CharField(choices=[('miqdor', 'Aniq miqdor (summa)'), ('foiz', 'Foiz (baza tannarxga nisbatan)')], default='miqdor', help_text="Har bir firma har xil ishlaydi — ba'zilari aniq summa, ba'zilari baza tannarxdan foiz sifatida hisoblaydi", max_length=10),
        ),
        migrations.AlterField(
            model_name='mahsulotqoshimchaxarajat',
            name='summa',
            field=models.DecimalField(decimal_places=2, help_text="turi='miqdor' bo'lsa — 1 donaga to'g'ri keladigan qo'shimcha xarajat (so'm); turi='foiz' bo'lsa — baza tannarxga nisbatan foiz (masalan 5 = 5%)", max_digits=10),
        ),
    ]
