# Generated by Django 5.1.15 on 2026-07-30 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0080_mahsulotqoshimchaxarajat_turi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serial',
            name='chiqarilgan_at',
            field=models.DateTimeField(blank=True, help_text='Omboradan chiqarilgan (yuklamaga olingan) vaqt', null=True),
        ),
        migrations.AddField(
            model_name='serial',
            name='yetkazib_beruvchi',
            field=models.ForeignKey(blank=True, help_text='Bu donani omboradan kim olib chiqqani (yuklama tasdiqlanganda yoziladi)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olib_chiqilgan_seriallar', to='main.yetkazibberuvchi'),
        ),
        migrations.CreateModel(
            name='SerialHarakat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('yaratildi', 'Ishlab chiqarildi'), ('chiqarildi', 'Omboradan chiqarildi (yuklama)'), ('sotildi', 'Sotildi'), ('qaytarildi', 'Qaytarildi')], max_length=15)),
                ('izoh', models.CharField(blank=True, default='', max_length=255)),
                ('vaqt', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_harakatlari', to='main.company')),
                ('serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harakatlar', to='main.serial')),
                ('user', models.ForeignKey(blank=True, help_text='Hodisani amalga oshirgan xodim (ishlab chiqaruvchi / yetkazib beruvchi / sotuvchi)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Serial harakati',
                'verbose_name_plural': 'Serial harakatlari',
                'ordering': ['-vaqt'],
            },
        ),
    ]
