# Generated by Django 5.0.6 on 2026-07-30 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0081_serial_chiqarilgan_at_serial_yetkazib_beruvchi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='miqdorqoshish',
            name='source_material_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miqdor_qoshishlar', to='main.productionmaterialrequest'),
        ),
    ]
