# Generated by Django 5.0.6 on 2026-07-31 11:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0082_miqdorqoshish_source_material_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rejalashtirilgan_miqdor', models.FloatField(help_text='Maqsad miqdor, masalan 100 dona')),
                ('sana', models.DateField(default=django.utils.timezone.now, help_text='Qaysi kun uchun vazifa')),
                ('status', models.CharField(choices=[('open', 'Ochiq'), ('claimed', 'Band qilingan'), ('done', 'Bajarildi'), ('cancelled', 'Bekor qilindi')], default='open', max_length=20)),
                ('kod', models.CharField(default=uuid.uuid4, editable=False, help_text='Vazifa QR kodi — chop etib taxtaga yopishtirish uchun', max_length=64, unique=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_tasks', to='main.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yaratgan_vazifalar', to=settings.AUTH_USER_MODEL)),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_tasks', to='main.mahsulot')),
                ('pazanda', models.ForeignKey(blank=True, help_text="Kim oldi (band qilingach to'ldiriladi)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olingan_vazifalar', to='main.pazanda')),
            ],
            options={
                'verbose_name': 'Ishlab chiqarish vazifasi',
                'verbose_name_plural': 'Ishlab chiqarish vazifalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='miqdorqoshish',
            name='source_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miqdor_qoshishlar', to='main.productiontask'),
        ),
        migrations.CreateModel(
            name='TaskMaterialPickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_qty', models.FloatField(help_text='BOM.norma_miqdor * task.rejalashtirilgan_miqdor')),
                ('measured_qty', models.FloatField(blank=True, null=True)),
                ('tasdiqlangan', models.BooleanField(default=False)),
                ('tasdiqlangan_at', models.DateTimeField(blank=True, null=True)),
                ('komponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_pickuplari', to='main.mahsulot')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_pickups', to='main.productiontask')),
            ],
            options={
                'verbose_name': 'Vazifa xom ashyo olib chiqishi',
                'verbose_name_plural': 'Vazifa xom ashyo olib chiqishlari',
                'unique_together': {('task', 'komponent')},
            },
        ),
    ]
