# Generated by Django 5.0.6 on 2026-07-31 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0083_productiontask_miqdorqoshish_source_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productiontask',
            name='qadoq_hajmi',
            field=models.PositiveIntegerField(blank=True, help_text="Faqat mahsulot serial_granularity='batch' bo'lganda majburiy — 1 QR kod nechta donadan iborat qadoqni ifodalashi (masalan 3) — reja miqdoriga bo'linmasa, qoldiq alohida-alohida (1 donalik) QR kodlar bilan chiqariladi", null=True),
        ),
        migrations.AddField(
            model_name='serial',
            name='dona_soni',
            field=models.PositiveIntegerField(default=1, help_text="Bu QR kod nechta mahsulot donasini ifodalaydi — 'unit' granularityda har doim 1, 'batch'da qadoqlash hajmiga qarab (masalan 3talik qadoq bo'lsa 3, qoldiq bo'lsa 1)"),
        ),
        migrations.AlterField(
            model_name='productiontask',
            name='status',
            field=models.CharField(choices=[('open', 'Ochiq'), ('claimed', 'Band qilingan'), ('producing', 'Ishlab chiqarilmoqda'), ('done', 'Bajarildi'), ('cancelled', 'Bekor qilindi')], default='open', max_length=20),
        ),
    ]
