# Generated by Django 5.0.6 on 2026-08-02 13:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0084_productiontask_qadoq_hajmi_serial_dona_soni_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='XodimMaosh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oylik_maosh', models.DecimalField(decimal_places=2, default=0, help_text="Oylik belgilangan maosh — firma 'Oylik (fiksval)' rejimida yoki xodim ishlab chiqaruvchi bo'lmaganda ishlatiladi.", max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.company')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maosh_sozlamasi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Xodim oylik maoshi',
                'verbose_name_plural': 'Xodim oylik maoshlari',
            },
        ),
        migrations.CreateModel(
            name='XodimOyYopish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yil', models.PositiveSmallIntegerField()),
                ('oy', models.PositiveSmallIntegerField()),
                ('ishlab_topgan', models.DecimalField(decimal_places=2, max_digits=12)),
                ('avanslar_jami', models.DecimalField(decimal_places=2, max_digits=12)),
                ('hisoblangan_qoldiq', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tolangan_yakuniy_summa', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('manba', models.CharField(choices=[('per_unit', 'Ishlab chiqarilganga qarab'), ('fixed', 'Belgilangan oylik')], max_length=20)),
                ('izoh', models.TextField(blank=True, null=True)),
                ('yopilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oy_yopishlar', to=settings.AUTH_USER_MODEL)),
                ('yopgan_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Oylik yopish',
                'verbose_name_plural': 'Oylik yopishlar',
                'ordering': ['-yil', '-oy'],
            },
        ),
        migrations.CreateModel(
            name='XodimTolov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi', models.CharField(choices=[('avans', 'Avans'), ('yakuniy', 'Oy yakuniy hisob-kitobi')], max_length=10)),
                ('summa', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sana', models.DateField(default=django.utils.timezone.now)),
                ('izoh', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('berdi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='berilgan_tolovlar', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.company')),
                ('oy_yopish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tolovlar', to='main.xodimoyyopish')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xodim_tolovlari', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Xodim to'lovi",
                'verbose_name_plural': "Xodim to'lovlari",
                'ordering': ['-sana', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='xodimoyyopish',
            constraint=models.UniqueConstraint(fields=('user', 'yil', 'oy'), name='unique_oy_yopish_per_user'),
        ),
    ]
