# Generated by Django 5.0.6 on 2026-08-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0085_xodimmaosh_xodimoyyopish_xodimtolov_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='web_session_key',
            field=models.CharField(blank=True, help_text='Joriy amaldagi veb-sessiya kaliti — yangi qurilmada login qilinganda eskisi CompanyMiddleware orqali avtomatik yopiladi (bitta faol veb-sessiya qoidasi).', max_length=40, null=True),
        ),
    ]
