# Generated by Django 5.0.6 on 2026-08-03 10:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0086_user_web_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agent_qr_nonce',
            field=models.CharField(default=uuid.uuid4, editable=False, help_text="Desktop Agent QR-login shifrlangan payload'ining bir qismi — 'Yangilash' bosilganda o'zgaradi, shu orqali eski ko'rsatilgan/chop etilgan QR kod bekor bo'ladi.", max_length=64),
        ),
    ]
