# Generated by Django 5.0.6 on 2026-08-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0087_user_agent_qr_nonce'),
    ]

    operations = [
        migrations.AddField(
            model_name='miqdorqoshish',
            name='labels_printed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productiontask',
            name='status',
            field=models.CharField(choices=[('open', 'Ochiq'), ('claimed', 'Band qilingan'), ('materials_ready', 'Xom ashyo tortildi — "Ish bitdi" kutilmoqda'), ('producing', 'Ishlab chiqarilmoqda'), ('done', 'Bajarildi'), ('cancelled', 'Bekor qilindi')], default='open', max_length=20),
        ),
    ]
