# Generated by Django 5.0.6 on 2026-08-03 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0088_miqdorqoshish_labels_printed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miqdorqoshish',
            name='source_task',
            field=models.ForeignKey(blank=True, help_text='Har bir vazifada FAQAT bitta MiqdorQoshish/Serial partiyasi bo\'lishi mumkin — bu DB darajasidagi cheklov "Ish bitdi" ikki marta bosilib (real sinovda kuzatilgan) dublikat QR-yorliq yaratilishining oldini oladi.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miqdor_qoshishlar', to='main.productiontask', unique=True),
        ),
    ]
