# Generated by Django 5.1.15 on 2026-08-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0089_alter_miqdorqoshish_source_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serialharakat',
            name='event',
            field=models.CharField(choices=[('yaratildi', 'Ishlab chiqarildi'), ('chiqarildi', 'Omboradan chiqarildi (yuklama)'), ('sotildi', 'Sotildi'), ('qaytarildi', 'Qaytarildi'), ('shubhali', 'Shubhali — sotilmagan holda ombordan tashqarida skanerlandi')], max_length=15),
        ),
    ]
