# Generated by Django 5.1.15 on 2026-08-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0090_alter_serialharakat_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='xodimtolov',
            name='rasm',
            field=models.ImageField(blank=True, help_text="To'lov cheki/kvitansiyasi rasmi — qolib ketgan oylikni to'lashda majburiy.", null=True, upload_to='xodim_tolovlar/'),
        ),
    ]
