# Generated by Django 5.1.15 on 2026-08-05 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0091_xodimtolov_rasm'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Masalan: 1.4.0', max_length=30)),
                ('file', models.FileField(upload_to='agent_releases/')),
                ('izoh', models.TextField(blank=True, default='', help_text="Bu versiyada nima o'zgargani (changelog)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent versiyasi',
                'verbose_name_plural': 'Agent versiyalari',
                'ordering': ['-created_at'],
            },
        ),
    ]
