# Generated by Django 5.1.15 on 2026-08-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0092_agentrelease'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmaterialpickup',
            name='poured_qty',
            field=models.FloatField(default=0),
        ),
    ]
