# Generated by Django 5.1.15 on 2026-08-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0093_taskmaterialpickup_poured_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ish_haqi_turi_override',
            field=models.CharField(blank=True, choices=[('', 'Firma standarti'), ('fixed', 'Oylik (fiksval)'), ('per_unit', 'Ishlab chiqarilgan mahsulotga qarab')], default='', help_text="Bo'sh bo'lsa Company.ish_haqi_turi (firma standarti) ishlatiladi — faqat shu xodim uchun boshqacha to'lov turi kerak bo'lsa to'ldiriladi.", max_length=20),
        ),
    ]
