# Generated by Django 5.1.15 on 2026-08-10 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0094_user_ish_haqi_turi_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='qaytarish_javobgarligi',
            field=models.CharField(choices=[('yoq', "Yo'q — shunchaki chiqim (hech kimga qarz yozilmaydi)"), ('yetkazib_beruvchi', 'Yetkazib beruvchiga qarz'), ('savdogar', 'Savdogarga qarz')], default='yoq', max_length=20),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='kutilgan_ishlab_chiqarish_soat',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Ixtiyoriy — shu mahsulot uchun vazifa qancha soatda tugatilishi kutiladi (masalan 2.5). Bo'sh qoldirilsa, vazifaga muddat belgilanmaydi (KPI'da muddatga rioya ko'rsatkichi hisoblanmaydi).", max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='productiontask',
            name='muddat',
            field=models.DateTimeField(blank=True, help_text="Vazifa band qilingan (`claimed_at`) paytda, agar mahsulotda `kutilgan_ishlab_chiqarish_soat` belgilangan bo'lsa, avtomatik hisoblanadi — `claimed_at` + shu soat. Bo'sh bo'lsa vazifa muddatsiz (KPI'da hisobga olinmaydi).", null=True),
        ),
        migrations.AddField(
            model_name='qaytarilgan_mahsulotlar',
            name='harakat_turi',
            field=models.CharField(blank=True, choices=[('utilizatsiya', "Utilizatsiya (chiqim, ombor qoldig'iga qo'shilmaydi)"), ('qayta_ishlash', 'Qayta ishlash (xom ashyoga aylantiriladi)')], help_text="Faqat tasdiqlanganda (status=approved) to'ldiriladi.", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='qaytarilgan_mahsulotlar',
            name='javobgar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qaytarish_qarzlari', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qaytarilgan_mahsulotlar',
            name='komponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qayta_ishlangan_qaytarishlar', to='main.mahsulot'),
        ),
        migrations.AddField(
            model_name='qaytarilgan_mahsulotlar',
            name='komponent_miqdor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qaytarilgan_mahsulotlar',
            name='qarz_summasi',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Javobgarga yozilgan qarz summasi (mahsulot tannarxi * miqdor).', max_digits=12),
        ),
        migrations.AddField(
            model_name='qaytarilgan_mahsulotlar',
            name='yetkazib_beruvchi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qaytargan_mahsulotlar', to='main.yetkazibberuvchi'),
        ),
    ]
