# Generated by Django 5.0.6 on 2026-08-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0095_company_qaytarish_javobgarligi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='savdo_birlik_narxi',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Har bir sotuv uchun to'lanadigan komissiya summasi (ish_haqi_turi_override='per_sale' bo'lsa ishlatiladi) — savdogarga o'zi sotgan, yetkazib beruvchiga o'zi yetkazgan har bir savdo uchun.", max_digits=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='ish_haqi_turi_override',
            field=models.CharField(blank=True, choices=[('', 'Firma standarti'), ('fixed', 'Oylik (fiksval)'), ('per_unit', 'Ishlab chiqarilgan mahsulotga qarab'), ('per_sale', 'Sotilgan/yetkazilgan mahsulotga qarab (komissiya)')], default='', help_text="Bo'sh bo'lsa Company.ish_haqi_turi (firma standarti) ishlatiladi — faqat shu xodim uchun boshqacha to'lov turi kerak bo'lsa to'ldiriladi. 'per_sale' faqat savdogar/yetkazib_beruvchi uchun ma'noli.", max_length=20),
        ),
    ]
