# Generated by Django 5.0.6 on 2026-08-11 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0096_user_savdo_birlik_narxi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='savdo_birlik_narxi',
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='sotuv_ish_haqi_narxi',
            field=models.DecimalField(decimal_places=2, default=0, help_text="1 dona sotilgani/yetkazilgani uchun savdogar/yetkazib beruvchiga to'lanadigan summa — tannarxga qo'shiladi (ishlab_chiqarish_narxi kabi), sotuv sodir bo'lganda Savdo.ish_haqi_summasi'ga yig'iladi.", max_digits=10),
        ),
        migrations.AddField(
            model_name='savdo',
            name='ish_haqi_summasi',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Shu savdo bo'yicha savdogar/yetkazib beruvchiga tegishli ish haqi yig'indisi (sotilgan mahsulotlarning sotuv_ish_haqi_narxi asosida) — informatsion snapshot, foyda hisobida allaqachon ayirilgan (tannarx orqali).", max_digits=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='ish_haqi_turi_override',
            field=models.CharField(blank=True, choices=[('', 'Firma standarti'), ('fixed', 'Oylik (fiksval)'), ('per_unit', 'Ishlab chiqarilgan mahsulotga qarab'), ('per_sale', 'Sotilgan/yetkazilgan mahsulotga qarab')], default='', help_text="Bo'sh bo'lsa Company.ish_haqi_turi (firma standarti) ishlatiladi — faqat shu xodim uchun boshqacha to'lov turi kerak bo'lsa to'ldiriladi. 'per_sale' faqat savdogar/yetkazib_beruvchi uchun ma'noli — shu oyda amalga oshirgan savdolaridagi Savdo.ish_haqi_summasi (mahsulotning sotuv_ish_haqi_narxi asosida) yig'indisidan hisoblanadi.", max_length=20),
        ),
    ]
