# Generated by Django 5.0.6 on 2026-08-11 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0097_remove_user_savdo_birlik_narxi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KpiQoida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xodim_turi', models.CharField(choices=[('ishlab_chiqaruvchi', 'Ishlab chiqaruvchi'), ('savdogar', 'Savdogar'), ('yetkazib_beruvchi', 'Yetkazib beruvchi')], max_length=25)),
                ('olchov_turi', models.CharField(choices=[('dona', 'Dona (soni)'), ('summa', "Summa (so'm)")], default='summa', max_length=10)),
                ('chegara', models.DecimalField(decimal_places=2, help_text="Shu songa (yoki undan ko'p) yetilsa, bonus ishga tushadi.", max_digits=14)),
                ('bonus_turi', models.CharField(choices=[('fiks', 'Fiks summa (chegaraga yetsa, bir martalik)'), ('foiz', "Foiz (erishilgan summadan) — faqat 'Summa' o'lchovida")], default='fiks', max_length=10)),
                ('bonus_qiymati', models.DecimalField(decimal_places=2, help_text="'Fiks' bo'lsa — so'm, 'Foiz' bo'lsa — foiz (masalan 3 = 3%).", max_digits=14)),
                ('faol', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_qoidalari', to='main.company')),
                ('mahsulot', models.ForeignKey(blank=True, help_text="Bo'sh bo'lsa — jami (barcha mahsulotlar bo'yicha oylik jami) hisoblanadi.", null=True, on_delete=django.db.models.deletion.CASCADE, to='main.mahsulot')),
            ],
            options={
                'verbose_name': 'KPI qoidasi',
                'verbose_name_plural': 'KPI qoidalari',
                'ordering': ['xodim_turi', 'chegara'],
            },
        ),
    ]
