# Generated by Django 5.0.6 on 2026-08-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0098_kpiqoida'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tarozi_majburiy',
            field=models.BooleanField(default=True, help_text="O'chirilsa, Desktop Agent tarozini qidirmaydi va tortish ekranida shunchaki 'Oldim' tugmasi ko'rsatiladi."),
        ),
    ]
