# Generated by Django 5.0.6 on 2026-08-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0099_company_tarozi_majburiy'),
    ]

    operations = [
        migrations.AddField(
            model_name='serial',
            name='chop_etilmadi',
            field=models.BooleanField(default=False, help_text="Oxirgi chop etish urinishi muvaffaqiyatsiz bo'ldi (qog'oz tugagan, printer oflayn va h.k.) — keyingi badge skanida qayta chop etishga taklif qilinadi."),
        ),
        migrations.AddField(
            model_name='serial',
            name='chop_etish_sababi',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
