# Generated by Django 5.0.6 on 2026-08-12 11:18

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0100_serial_chop_etilmadi_serial_chop_etish_sababi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='agent_qr_nonce',
            field=models.CharField(default=main.models._gen_agent_qr_nonce, editable=False, help_text="Desktop Agent QR-login shifrlangan payload'ining bir qismi — 'Yangilash' bosilganda o'zgaradi, shu orqali eski ko'rsatilgan/chop etilgan QR kod bekor bo'ladi. Qasddan QISQA (16 belgi, to'liq UUID emas) — bu QR-login payload'ining bir qismi, uzunligi shifrlangan QR'ning zichligiga (kamerada o'qish qulayligiga) bevosita ta'sir qiladi, alohida maxfiy token sifatida ishlatilmaydi.", max_length=64),
        ),
    ]
