# Generated by Django 5.0.6 on 2026-08-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0101_alter_user_agent_qr_nonce'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='shtrix_kod',
            field=models.CharField(blank=True, default='', help_text="Real shtrix-kod (EAN/UPC va h.k.) — Desktop Agent orqali savdogar sotuvida mahsulotni tez topish uchun (faqat Desktop Agent tarifida ma'noli).", max_length=32),
        ),
    ]
