# Generated by Django 5.0.6 on 2026-08-17 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0102_mahsulot_shtrix_kod'),
    ]

    operations = [
        migrations.AddField(
            model_name='haridordukon',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text="Bu do'konni kim qo'shgani — sotuv sahifasida shu foydalanuvchining o'zi yaratgan do'konlarini birinchi ko'rsatish uchun.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yaratgan_dukonlar', to=settings.AUTH_USER_MODEL),
        ),
    ]
