# Generated by Django 5.0.6 on 2026-08-18 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0103_haridordukon_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavdoMahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('miqdor', models.FloatField()),
                ('narx', models.FloatField()),
                ('mahsulot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='savdo_qatorlari', to='main.mahsulot')),
                ('savdo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.savdo')),
            ],
        ),
    ]
