# Generated by Django 5.0.6 on 2026-10-07 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0104_savdomahsulot'),
    ]

    operations = [
        migrations.AddField(
            model_name='haridordukon',
            name='yetkazib_beruvchi',
            field=models.ForeignKey(blank=True, help_text="Bu do'konga biriktirilgan yetkazib beruvchi — xaritada do'kon shu yetkazib beruvchining rangida ko'rsatiladi.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biriktirilgan_dukonlar', to='main.yetkazibberuvchi'),
        ),
    ]
