# Generated by Django 5.0.6 on 2026-10-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0105_haridordukon_yetkazib_beruvchi'),
    ]

    operations = [
        migrations.AddField(
            model_name='yetkazibberuvchi',
            name='rang',
            field=models.CharField(blank=True, default='', help_text="Xaritada ko'rsatiladigan rang (#rrggbb). Bo'sh bo'lsa avtomatik tanlanadi.", max_length=7),
        ),
    ]
