"""
Django settings for crm project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    raise ImproperlyConfigured(
        "SECRET_KEY .env faylida o'rnatilmagan. Xavfsizlik uchun standart "
        "qiymat ishlatilmaydi — .env fayliga SECRET_KEY=<uzun tasodifiy qator> qo'shing."
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

if DEBUG:
    ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',')
else:
    _allowed_hosts_env = os.getenv('ALLOWED_HOSTS', '')
    if not _allowed_hosts_env:
        raise ImproperlyConfigured(
            "DEBUG=False bo'lganda ALLOWED_HOSTS .env faylida aniq ro'yxat "
            "sifatida ko'rsatilishi shart (masalan: stockfirm.uz,*.stockfirm.uz)."
        )
    ALLOWED_HOSTS = _allowed_hosts_env.split(',')

CSRF_TRUSTED_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',')
if not any(CSRF_TRUSTED_ORIGINS):
    CSRF_TRUSTED_ORIGINS = [
        'https://stockfirm.uz',
        'https://www.stockfirm.uz',
        'https://admin.stockfirm.uz',
        'https://*.stockfirm.uz',
    ]




# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'rest_framework',
    'main',
    'landing',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'main.middleware.CompanyMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

ROOT_URLCONF = 'crm.urls'
ASGI_APPLICATION = 'crm.asgi.application'

REDIS_URL = os.getenv('REDIS_URL')
_use_redis_channel_layer = REDIS_URL or os.getenv('USE_REDIS_CHANNEL_LAYER', '').lower() in ('1', 'true', 'yes')

if _use_redis_channel_layer:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [REDIS_URL or 'redis://redis:6379/0'],
            },
        },
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'main.context_processors.plan_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'crm.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DB_ENGINE = os.getenv('DB_ENGINE', 'sqlite').lower()

if DB_ENGINE == 'mysql':
    DATABASES = {
        'default': {
            'ENGINE': os.getenv('DB_BACKEND', 'mysql.connector.django'),
            'NAME': os.getenv('DB_NAME'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST', '127.0.0.1'),
            'PORT': os.getenv('DB_PORT', '3306'),
            'OPTIONS': {
                'charset': 'utf8mb4',
            },
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.getenv('SQLITE_PATH', BASE_DIR / 'db.sqlite3'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/


LANGUAGE_CODE = 'uz-latn'  # yoki 'ru' yoki 'en-us'

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles' 
SERVE_STATIC_FILES = os.getenv('SERVE_STATIC_FILES', 'True') == 'True'


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
SERVE_MEDIA_FILES = os.getenv('SERVE_MEDIA_FILES', 'True') == 'True'

AUTH_USER_MODEL = 'main.User' 
AUTHENTICATION_BACKENDS = [
    'main.auth_backends.CompanyAwareModelBackend',
]
SILENCED_SYSTEM_CHECKS = ['auth.W004']

# Default primary key field typex
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# Sessiya muddati: 7 kun (7 * 24 * 60 * 60 soniya)
SESSION_COOKIE_AGE = 7 * 24 * 60 * 60  # 604800 soniya

# Har so‘rovda sessiya muddati cho‘zilsin
SESSION_SAVE_EVERY_REQUEST = True

# Brauzer yopilganda tugamasin
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# Telegram Bot Settings
TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN', '')
if not DEBUG and not TELEGRAM_BOT_TOKEN:
    raise ValueError("TELEGRAM_BOT_TOKEN muhit o'zgaruvchisi production muhitda majburiy.")
BASE_DOMAIN = os.getenv('BASE_DOMAIN', 'stockfirm.uz')
LANDING_DOMAINS = [
    domain.strip().split(':')[0]
    for domain in os.getenv('LANDING_DOMAINS', f'{BASE_DOMAIN},www.{BASE_DOMAIN}').split(',')
    if domain.strip()
]
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
LOGIN_URL = '/login/'

# Production xavfsizlik sozlamalari (faqat DEBUG=False bo'lganda) — nginx
# HTTPS orqali proxy qilishi va SECURE_PROXY_SSL_HEADER to'g'ri sozlangan
# bo'lishi kerak, aks holda SECURE_SSL_REDIRECT redirect-loop keltirib
# chiqarishi mumkin.
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000  # 1 yil
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
